apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: pycsw
  name: pycsw
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  selector:
    io.kompose.service: pycsw
status:
  loadBalancer: {}
